### ISSUE TITLE
New set of images

### ISSUE THREAD

**Issue by byelik** [leo6104/ngx-slick-carousel#66]
Hi,
I have a simple app with carousel. At the start I set images for the carousel, but some times I need to update carousel with totally new images. But when I receive a new data I get the next error:
`ERROR DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.
    at EmulatedEncapsulationDomRenderer2.insertBefore (http://localhost:4200/vendor.js:102696:20)
    at BaseAnimationRenderer.insertBefore (http://localhost:4200/vendor.js:137307:23)
    at nativeInsertBefore (http://localhost:4200/vendor.js:14923:18)
    at applyToElementOrContainer (http://localhost:4200/vendor.js:14503:13)
    at applyNodes (http://localhost:4200/vendor.js:15111:17)
    at applyView (http://localhost:4200/vendor.js:15118:5)
    at addViewToContainer (http://localhost:4200/vendor.js:14556:5)
    at ViewContainerRef.insert (http://localhost:4200/vendor.js:15838:21)
    at ViewContainerRef.createEmbeddedView (http://localhost:4200/vendor.js:15784:22)
    at http://localhost:4200/vendor.js:53705:50`

Could you please clarify how to update my carousel with new porion of images?
Thanks in advance!

**Comment by byelik** [comment]
'trackBy' fixed the issue
